# Generated by Django 6.0.3 on 2026-03-26 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "detection_type",
                    models.CharField(
                        choices=[("image", "图片检测"), ("video", "视频检测")],
                        max_length=10,
                        verbose_name="检测类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="检测时间"),
                ),
                ("summary", models.JSONField(default=dict, verbose_name="摘要信息")),
                (
                    "report_file",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="报告文件路径",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "检测历史",
                "verbose_name_plural": "检测历史",
                "ordering": ["-created_at"],
            },
        ),
    ]
