# Generated by Django 6.0.3 on 2026-03-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fruit_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detectionhistory",
            name="detection_type",
            field=models.CharField(
                choices=[
                    ("image", "图片检测"),
                    ("video", "视频检测"),
                    ("realtime", "实时检测"),
                ],
                max_length=10,
                verbose_name="检测类型",
            ),
        ),
    ]
