# Generated by Django 6.0.3 on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_api', '0002_alter_detectionhistory_detection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionhistory',
            name='detection_type',
            field=models.CharField(
                choices=[
                    ('image', 'Image Detection'),
                    ('video', 'Video Detection'),
                    ('realtime', 'Realtime Detection'),
                    ('diameter', 'Diameter Measurement'),
                ],
                max_length=10,
                verbose_name='Detection Type',
            ),
        ),
    ]
