# Generated by Django 6.0.3 on 2026-04-02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_api', '0003_alter_detectionhistory_detection_type_add_diameter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProcessingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Task ID')),
                ('original_file_name', models.CharField(max_length=255, verbose_name='Original File Name')),
                ('input_path', models.CharField(max_length=500, verbose_name='Input File Path')),
                ('output_path', models.CharField(max_length=500, verbose_name='Output File Path')),
                ('process_fps', models.PositiveIntegerField(default=5, verbose_name='Process FPS')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='processing', max_length=16, verbose_name='Status')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='Progress')),
                ('processed_frames', models.PositiveIntegerField(default=0, verbose_name='Processed Frames')),
                ('total_frames', models.PositiveIntegerField(default=0, verbose_name='Total Frames')),
                ('frame_rate', models.FloatField(default=0, verbose_name='Frame Rate')),
                ('video_width', models.PositiveIntegerField(default=0, verbose_name='Video Width')),
                ('video_height', models.PositiveIntegerField(default=0, verbose_name='Video Height')),
                ('message', models.CharField(default='任务已创建', max_length=255, verbose_name='Message')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Error')),
                ('report_data', models.JSONField(blank=True, null=True, verbose_name='Report Data')),
                ('report_file', models.CharField(blank=True, max_length=500, null=True, verbose_name='Report File')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Video Processing Task',
                'verbose_name_plural': 'Video Processing Task',
                'ordering': ['-created_at'],
            },
        ),
    ]
