"""
Django settings for shuiguo project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-9mvbwht*#kz5+*ph0xyg=k5%igoqwwuoqquz8&gvy8=p+fa=o4"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "fruit_api",
    "rest_framework"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "shuiguo.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "shuiguo.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'shuiguo_db',          # 数据库名，需预先创建
        'USER': 'root',
        'PASSWORD': '105474',
        'HOST': 'localhost',            # 或者你的 MySQL 主机
        'PORT': '3306',                 # MySQL 默认端口
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
# 媒体文件配置（用于保存报告文件）
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
MODEL_CONFIG = {
    # 模型文件夹基础路径 (相对于项目根目录)
    'BASE_DIR': BASE_DIR / 'model',

    # 模型文件名
    'FRUIT_MODEL': 'best_model_finetuned.pth',
    'MANGO_MODEL': 'mango_mobilevit_plus.pth',
    'BANANA_MODEL': 'banana_mobilevit_plus.pth',
    'STRAWBERRY_MODEL': 'strawberry_3class_mobilevit.pth',
    'YOLO_MODEL': 'epoch90.pt',

    # 水果分类类别列表
    'FRUIT_CLASS_NAMES': [
        '苹果', '鳄梨', '香蕉', '甜菜根', '黑莓', '蓝莓', '西兰花', '卷心菜',
        '辣椒', '胡萝卜', '花椰菜', '辣椒', '玉米', '黄瓜', '枣',
        '火龙果', '茄子', '无花果', '大蒜', '生姜', '葡萄', '番石榴', '墨西哥辣椒',
        '猕猴桃', '柠檬', '生菜', '芒果', '蘑菇', '秋葵', '橄榄', '洋葱', '橙子',
        '辣椒粉', '花生', '梨', '豌豆', '菠萝', '石榴', '土豆', '南瓜',
        '萝卜', '红毛丹', '大豆', '菠菜', '草莓', '甜玉米', '红薯',
        '番茄', '芜菁', '西瓜'
    ],

    # 预处理参数
    'PREPROCESS': {
        'FRUIT': {
            'RESIZE': 256,
            'CROP': 224,
            'MEAN': [0.485, 0.456, 0.406],
            'STD': [0.229, 0.224, 0.225],
        },
        'RIPENESS': {
            'RESIZE': (256, 256),
            'MEAN': [0.485, 0.456, 0.406],
            'STD': [0.229, 0.224, 0.225],
        },
    },

    # 支持熟度检测的水果及对应的模型属性名和类别属性名
    'RIPENESS_SUPPORTED': {
        '芒果': {'model_attr': 'mango_model', 'classes_attr': 'mango_classes'},
        '香蕉': {'model_attr': 'banana_model', 'classes_attr': 'banana_classes'},
        '草莓': {'model_attr': 'strawberry_model', 'classes_attr': 'strawberry_classes'},
    },
}

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',   # 前端开发服务器地址
    # 如果有其他前端地址（如生产环境），也一并加入
]